package org.remus.giteabot.prworkflow.unittest;

import org.remus.giteabot.prworkflow.unittest.coverage.CoverageResult;
import org.remus.giteabot.prworkflow.unittest.runner.UnitTestOutcome;
import org.remus.giteabot.prworkflow.unittest.runner.UnitTestOutcomeStatus;

import java.util.List;
import java.util.Locale;

/**
 * Renders the Markdown comment the unit-test-author workflow posts on a pull
 * request. Pure string assembly — no Spring, fully unit-testable.
 */
public final class UnitTestSummaryRenderer {

    private static final String HEADER = "## 🧪 AI Unit Tests";
    private static final String FOOTER = "\n\n---\n*Generated by AI Git Bot — review before merging.*";

    private UnitTestSummaryRenderer() {
        // utility
    }

    /** Immediate acknowledgement posted when the run starts. */
    public static String renderStarting(long prNumber, UnitTestFramework framework) {
        return HEADER + "\n\n"
                + "Generating unit tests for this pull request (toolchain: `"
                + framework.key() + "`). This can take a few minutes…" + FOOTER;
    }

    public static String renderSkipped(long prNumber, String reason) {
        return HEADER + "\n\n⏭️ **Skipped** — " + reason + FOOTER;
    }

    public static String renderFailed(long prNumber, String reason) {
        return HEADER + "\n\n❌ **Failed** — " + reason + FOOTER;
    }

    /**
     * Full result comment with the per-case table, the run outcome and the
     * coverage delta (when known).
     */
    public static String render(UnitTestSuite suite, UnitTestOutcome outcome, CoverageResult baseline) {
        StringBuilder sb = new StringBuilder(1024);
        sb.append(HEADER).append("\n\n");
        sb.append(statusBadge(outcome)).append("\n\n");

        List<UnitTestCase> cases = suite == null ? List.of() : suite.getCases();
        sb.append("**Toolchain:** `").append(suite == null ? "?" : suite.getFramework().key()).append("`  ");
        sb.append("**Generated:** ").append(cases.size()).append(" test file(s)\n\n");

        if (!cases.isEmpty()) {
            sb.append("| Test file | Status |\n|---|---|\n");
            for (UnitTestCase c : cases) {
                sb.append("| `").append(c.getPath()).append("` | ")
                        .append(statusEmoji(c.getLastStatus())).append(' ')
                        .append(c.getLastStatus()).append(" |\n");
            }
            sb.append('\n');
        }

        appendCoverage(sb, baseline, outcome.coverage());

        if (outcome.rawOutput() != null && !outcome.rawOutput().isBlank()
                && outcome.status() != UnitTestOutcomeStatus.PASSED) {
            sb.append("<details><summary>Runner output</summary>\n\n```\n")
                    .append(truncate(outcome.rawOutput(), 6000))
                    .append("\n```\n</details>\n");
        }

        return sb.append(FOOTER).toString();
    }

    private static void appendCoverage(StringBuilder sb, CoverageResult baseline, CoverageResult after) {
        if (after == null || !after.known()) {
            return;
        }
        sb.append(String.format(Locale.ROOT, "**Coverage:** %.1f%%", after.percent()));
        if (baseline != null && baseline.known()) {
            double delta = after.percent() - baseline.percent();
            String sign = delta >= 0 ? "+" : "";
            sb.append(String.format(Locale.ROOT, " (%s%.1f%% vs. baseline %.1f%%)",
                    sign, delta, baseline.percent()));
        }
        sb.append("\n\n");
    }

    private static String statusBadge(UnitTestOutcome outcome) {
        return switch (outcome.status()) {
            case PASSED -> "✅ **All " + outcome.attempted() + " generated test(s) passed.**";
            case FAILED -> "⚠️ **" + outcome.failed() + " of " + outcome.attempted()
                    + " generated test(s) failed.** " + outcome.summary();
            case SKIPPED -> "⏭️ **Skipped** — " + outcome.summary();
            case ERROR -> "❌ **Error** — " + outcome.summary();
        };
    }

    private static String statusEmoji(UnitTestCaseStatus status) {
        return switch (status) {
            case PASSED -> "✅";
            case FAILED -> "❌";
            case FLAKY -> "🟡";
            case SKIPPED -> "⏭️";
            case ERROR -> "💥";
            case PENDING -> "⏳";
        };
    }

    private static String truncate(String s, int max) {
        if (s == null) {
            return "";
        }
        return s.length() <= max ? s : s.substring(0, max) + "\n…(truncated)";
    }
}

