-- Persistence for the unit-test-author PR workflow.
--
-- A unit_test_suites row groups every generated unit-test file for one
-- UnitTestWorkflow run on one PR. unit_test_cases holds the individual
-- generated test files plus their last execution outcome. The full file
-- content is stored inline (CLOB) so the bot can re-run / regenerate without
-- re-cloning anything. Mirrors pr_test_suites / pr_test_cases (the E2E
-- workflow) but for white-box unit tests committed onto the PR branch.
--
-- All additions are idempotent so the migration can be re-applied safely.

CREATE TABLE IF NOT EXISTS unit_test_suites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    pr_number BIGINT NOT NULL,
    framework VARCHAR(32) NOT NULL,
    source_tree_ref VARCHAR(255),
    lifecycle_mode VARCHAR(32) NOT NULL DEFAULT 'commit-to-pr',
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_unit_test_suites_run
        FOREIGN KEY (run_id) REFERENCES pr_workflow_runs(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_unit_test_suites_run_id ON unit_test_suites(run_id);
CREATE INDEX IF NOT EXISTS idx_unit_test_suites_pr_number ON unit_test_suites(pr_number);

CREATE TABLE IF NOT EXISTS unit_test_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suite_id BIGINT NOT NULL,
    path VARCHAR(1024) NOT NULL,
    title VARCHAR(512),
    content CLOB NOT NULL,
    last_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    last_run_at TIMESTAMP,
    last_duration_ms BIGINT,
    last_log CLOB,
    CONSTRAINT fk_unit_test_cases_suite
        FOREIGN KEY (suite_id) REFERENCES unit_test_suites(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_unit_test_cases_suite_id ON unit_test_cases(suite_id);

