-- V36: Outgoing webhooks — admin-configured endpoints and durable delivery attempts.
-- secret / authorization_header hold AES-GCM ciphertext (Base64), like ai_integrations.api_key.
-- Delivery rows in PENDING/RETRYING are in-flight work and must never be pruned.

CREATE TABLE IF NOT EXISTS event_hook_endpoint (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(200) NOT NULL,
    url                 VARCHAR(1024) NOT NULL,
    secret              VARCHAR(1000),
    authorization_header VARCHAR(1000),
    skip_tls_verify     BOOLEAN NOT NULL DEFAULT FALSE,
    enabled             BOOLEAN NOT NULL DEFAULT TRUE,
    event_types         VARCHAR(1024) NOT NULL,
    custom_headers      TEXT,
    bot_id              BIGINT,
    repo_owner          VARCHAR(255),
    repo_name           VARCHAR(255),
    created_at          TIMESTAMP NOT NULL,
    updated_at          TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS event_hook_delivery (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_uuid       VARCHAR(36) NOT NULL,
    endpoint_id         BIGINT NOT NULL,
    event_type          VARCHAR(80) NOT NULL,
    payload_json        TEXT NOT NULL,
    status              VARCHAR(20) NOT NULL,
    attempts            INT NOT NULL DEFAULT 0,
    next_attempt_at     TIMESTAMP,
    last_response_code  INT,
    last_error          VARCHAR(2000),
    created_at          TIMESTAMP NOT NULL,
    completed_at        TIMESTAMP,
    CONSTRAINT fk_event_hook_delivery_endpoint
        FOREIGN KEY (endpoint_id) REFERENCES event_hook_endpoint(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_event_hook_delivery_due ON event_hook_delivery (status, next_attempt_at);
CREATE INDEX IF NOT EXISTS idx_event_hook_delivery_endpoint ON event_hook_delivery (endpoint_id, id);
